import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

List englishGender = ['male', 'female'];
List arabicGender = ['ذكر', 'انثى'];

List englishCars = [
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'BMW',
  'Baic',
  'Bestune',
  'Brilliance',
  'Byd',
  'Cadillac',
  'Canghe',
  'Changan',
  'Chery',
  'Chevrolet',
  'Citroën',
  'Cupra',
  'DAIHATSU',
  'DAWEOO',
  'DFSK',
  'DODGE',
  'Dongfeng',
  'Ferrari',
  'Fiat',
  'Ford',
  'Forthing',
  'GMC',
  'Geely',
  'Haval',
  'Honda',
  'Hyundai',
  'Jac',
  'Jaguar',
  'Jeep',
  'Jetour',
  'KIA',
  'Lada',
  'Land Rover',
  'Lexus',
  'MG',
  'Maserati',
  'Mazda',
  'Mercedes Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Porsche',
  'Proton',
  'Renault',
  'Seat',
  'Skoda',
  'Ssang Yong',
  'Subaru',
  'Suzuki',
  'TESLA',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Zotye',
];
List arabicCars = [
  'أستون مارتن',
  'ألفا روميو',
  'أم جي',
  'أوبل',
  'أودي',
  'بايك',
  'بروتون',
  'بريلينس',
  'بورش',
  'بي إم دبليو',
  'بي وي دي',
  'بيستون',
  'تسانغ',
  'تسلا',
  'تشانجان',
  'تويوتا',
  'جاك',
  'جاكوار',
  'جي إم سي',
  'جيب',
  'جيتور',
  'جيلي',
  'دايهاتسو',
  'دايو',
  'دفسك',
  'دودج',
  'دونغفنغ',
  'رينو',
  'زوتي',
  'سانغ يونغ',
  'سكودا',
  'سوبارو',
  'سوزوكي',
  'سيات',
  'سيتروين',
  'شيري',
  'شيفروليه',
  'فورثينج',
  'فورد',
  'فولفو',
  'فولكس فاجن',
  'فيات',
  'فيراري',
  'كاديلاك',
  'كوبرا',
  'كيا',
  'لادا',
  'لاند روفر',
  'لكزس',
  'مازدا',
  'مازيراتي',
  'مرسيدس بنز',
  'ميتسوبيشي',
  'ميني',
  'نيسان',
  'هفال',
  'هوندا',
  'هيونداي',
];
List englishColors = [
  'black',
  'white',
  'grey',
  'silver',
  'red',
  'blue',
  'brown',
  'green',
  'beige',
  'orange',
  'gold',
  'yellow',
  'purple',
];
List arabicColors = [
  'أسود',
  'أبيض',
  'رمادي',
  'فضي',
  'أحمر',
  'أزرق',
  'بني',
  'أخضر',
  'بيج',
  'برتقالي',
  'ذهبي',
  'أصفر',
  'بنفسجي',
];
//
List<Widget> getColorWidgets() {
  return [
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.black,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.white,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.grey,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Color.fromRGBO(192, 192, 192, 1),
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.red,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.blue,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.brown,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.green,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Color.fromRGBO(245, 245, 220, 1),
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.orange,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.amber,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.yellow,
    ),
    const CircleAvatar(
      radius: 10,
      backgroundColor: Colors.purple,
    ),
  ];
}

//
List getDatesList() {
  List productionDates = [];
  for (int i = DateTime.now().year + 1; i >= 2000; i--) {
    productionDates.add(i);
  }
  return productionDates;
}
